var data_dict = {
  "accu_max_cell_temp": 1,
  "accu_min_cell_temp": 2,
  "accu_dcdc_temp": 3,
  "accu_max_humidity": 4,
  "accu_soc_energy": 5,
  "accu_total_voltage_vs": 6,
  "accu_accu_current": 7,
  "accu_max_cell_voltage": 8,
  "accu_min_cell_voltage": 9,
  "accu_wh_consumed": 10,
  "accu_ah_consumed": 11,
  "pdu_max_cell_temp": 12,
  "pdu_max_cell_voltage": 13,
  "pdu_min_cell_voltage": 14,
  "pdu_tdk1_current": 15,
  "pdu_tdk2_current": 16,
  "pdu_wh_consumed": 17,
  "inv_curr_lim_igbt_temp": 18,
  "inv_curr_lim_motor_temp": 19,
  "inv_no_power_supply_voltage": 20,
  "res_radio_quality": 21,
  "vcu_brake_front": 22,
  "vcu_brake_rear": 23,
  "vcu_actual_torque": 24,
  "vcu_requested_torque": 25,
  "vcu_motor_rpm": 26,
  "vcu_apps1": 27,
  "vcu_apps2": 28,
  "vcu_apps2": 29,
  "vcu_hall_fr": 30,
  "vcu_hall_fl": 31,
  "vcu_hall_rr": 32,
  "vcu_hall_rl": 33,
  "ccu_igbt_temp": 34,
  "ccu_motor_temp": 35,
  "plex_accel_long": 36,
  "plex_accel_lat": 37,
  "plex_gps_speed": 38,
  "asb_ebs_pressure": 39,
  "asb_brake_ctrl_temp": 40,
  "tpms_fr_temp": 41,
  "tpms_fr_press": 42,
  "tpms_fl_temp": 43,
  "tpms_fl_press": 44,
  "tpms_rr_temp": 45,
  "tpms_rr_press": 46,
  "ir_infrared_fr": 47,
  "ir_infrared_fl": 48,
  "ir_infrared_rr": 49,
  "ir_infrared_rl": 50,
  "can2usb_lap_counter": 51,
  "can2usb_brake_target": 52,
  "can2usb_speed_actual": 53,
  "can2usb_speed_target": 54,
  "can2usb_pc_temperature": 55,
  "can2usb_steering_ctrl_temp": 56,
  "can2usb_steering_target": 57,
  "tpms_rl_temp": 58,
  "tpms_rl_press": 59,
  "accu_bms_error_code": 60,
  "accu_tsac_error_code": 61,
  "inv_inv_enable": 62,
  "inv_inv_ok": 63,
  "inv_curr_lim_reached": 64,
  "inv_curr_peak_val_warn": 65,
  "inv_defective_param": 66,
  "inv_hardware_fault": 67,
  "inv_faulty_safety_circuit": 68,
  "inv_can_time_out_exceeded": 69,
  "inv_bad_encoder_signal": 70,
  "inv_overvoltage": 71,
  "inv_overcurrent": 72,
  "inv_current_measure_fault": 73,
  "inv_ballast_circuit_overload": 74,
  "inv_faulty_run_signal_emi": 75,
  "inv_inactive_rfe": 76,
  "inv_power_supply_missing_or_too_low": 77,
  "inv_output_voltage_limit_reached": 78,
  "inv_overcurrent_200": 79,
  "inv_ballast_circuit_overload_87": 80,
  "res_e_stop": 81,
  "res_k2_switch_status": 82,
  "res_k3_button_status": 83,
  "vcu_precharge_done": 84,
  "vcu_r2d_done": 85,
  "vcu_as_status": 86,
  "dash_r2d_pressed": 87,
  "dash_aux2_pressed": 88,
  "dash_regen_on": 89,
  "dash_aero_fans_on": 90,
  "dash_pc_combo": 91,
  "dash_mission_locked": 92,
  "dash_power_limiter": 93,
  "dash_traction_def": 94,
  "dash_mission": 95,
  "ccu_pumps_on": 96,
  "ccu_motor_temp_too_high": 97,
  "ccu_device_temp_too_high": 98,
  "ccu_motor_temp_limit_reached": 99,
  "ccu_device_temp_limit_reached": 100,
  "asb_pc_combo_ok": 101,
  "asb_brake_pressure_front_low": 102,
  "asb_ebs_relay_closed_error": 103,
  "asb_asms_on_error": 104,
  "asb_computer_error": 105,
  "asb_res_error": 106,
  "asb_as_status_error": 107,
  "asb_service_brake_error": 108,
  "asb_ebs_pressure_error": 109,
  "asb_manual_begin": 110,
  "asb_manual_asms_off": 111,
  "asb_manual_service_brake_unavailable": 112,
  "asb_manual_ebs_pressure_low": 113,
  "asb_manual_mission_error": 114,
  "asb_manual_asms_off_error": 115,
  "asb_manual_service_brake_unavailable_error": 116,
  "asb_manual_ebs_pressure_low_error": 117,
  "asb_as_relay_sdc": 118,
  "asb_asms_on": 119,
  "can2usb_vn_200_ok": 120,
  "can2usb_vn_300_ok": 121,
  "can2usb_camera_left_ok": 122,
  "can2usb_camera_right_ok": 123,
  "can2usb_clock_ok": 124,
  "can2usb_camera_inference_ok": 125,
  "can2usb_velocity_estimation_ok": 126,
  "can2usb_slam_ok": 127,
  "can2usb_mpc_controller_ok": 128,
  "can2usb_path_planning_ok": 129,
  "can2usb_pi_pp_controller_ok": 130,
  "can2usb_steering_ctrl_enab": 131,
  "can2usb_ins_mode": 132,
  "can2usb_steering_ctrl_error_code": 133,
  "asb_ebs_state": 134,
  "asb_service_brake_state": 135,
  "asb_init_check_started": 136,
  "asb_init_check_ended": 137,
  "asb_heartbeat": 138,
  "asb_autonomous_begin": 139,
  "asb_heartbeat_ack": 140,
  "asb_heartbeat_error": 141,
  "asb_ebs_proper_pressure": 142,
  "asb_brake_tr_f_front_ok": 143,
  "asb_brake_tr_f_rear_ok": 144,
  "asb_pc_combo_ok": 145,
  "asb_brake_pressure_front_low": 146,
  "asb_brake_pressure_front_high": 147,
  "asb_brake_pressure_rear_low": 148,
  "asb_brake_pressure_rear_high": 149,
  "asb_ebs_proper_pressure": 150,
  "asb_brake_tr_f_front_ok": 151,
  "asb_brake_tr_f_rear_ok": 152,
  "vcu_bspd_error": 153,
  "vcu_asb_error": 154,
  "asb_res_error": 155,
  "accu_imd_error": 156,
  "accu_ams_error": 157,
  "dash_bots_sd": 158,
  "dash_cockpit_sd": 159,
  "dash_inertia_sd": 160,
  "vcu_sd_closed": 161,
  "asb_sd_button_right": 162,
  "accu_over_60v_dclink": 163,
  "accu_air_m_state": 164,
  "accu_air_m_supp": 165,
  "accu_air_p_state": 166,
  "accu_air_p_supp": 167,
  "accu_precharge_state": 168,
  "accu_ts_active": 169,
  "asb_sd_button_left": 170
}


var container1 = "<div id="
var container2 = "class='left-container2 container'><div class='sensor1-chart-block block clear' style = 'position:relative;' id='add_to_me'> <button class = 'time_picker' style='float: left' id='currange' onclick='addCode()'>Time: from now-5m to now</button><button class='btn' onclick='fullscreen()' style=' float: right; z-index : 3; background-color:none; color:white;'><i class='fa fa-expand' style='z-index:3; color: white;'></i></button><div class='form-popup' style='position:absolute; z-index:4; top : 40px; left: 1px; ' id='myForm'><form action='/action_page.php' class='form-container'><div class='text'> From </div><input type='time'  id='from'  step='2' required ><div class='text'> To </div><input type='time'  id='to'  step='2' required ><button type='button' class='time_picker' onclick='saveForm()' style='display:inline'>Save</button><button type='button' class='time_picker' onclick='closeForm()' style='display:inline; float:right'>Close</button></form></div><div id='livegraph' class = live ><iframe src='http://localhost:3000/d-solo/WU_FjM8nz/prom?orgId=1&from=now-5m&to=now&theme=dark&panelId="
var container3 =  " id='chart-left' allowfullscreen = 'true' frameBorder='0' width='570' height='300'  style=' overflow-x: hidden; background-color: green; border: none; overflow: hidden; margin:0px !important; padding: 0px !important;'  frameborder='0'></iframe></div></div></div>"
function addCode(panelid) {
  panelid = 2*panelid
    document.getElementById("wrapper").innerHTML += container1+`'${panelid}' `+container2+ `${panelid}' `+ container3;    }
//fullscreen button
/*document.getElementById("myBtn").addEventListener("click", ()=>{
    document.documentElement.requestFullscreen().catch((e) => {
        console.log(e);
    });
});*/

function close_bottomcont() {
    document.getElementById("addcontainer").style.display = "none";
  }
  function open_bottomcont() {
      document.getElementById("addcontainer").style.display = "block";
    }
exports.data_dict = data_dict;
